site_name: Documentation
site_url: https://apisec-inc.github.io/documentation/
nav:
    - APIsec Overview: index.md
    - 1. Register an API: RegisterAPI.md
    - 2. Register an API Gateway: RegisterGateway.md
    - 3. Projects Section: ProjectSection.md
    - 4. Project Dashboard: ProjectDashboard.md
    - 5. Integrations: Integrations.md
    - Jira Issue Tracker Setup: SetupJiraTracker.md
    - 6. Reports: Reports.md
    - 7. Deploy Scanners: DeployScanners.md
    - 8. Vault: Vault.md
    - 9. Security Categories: SecurityCategories.md
    - 10. Global Dashboard: GlobalDashboard.md
    - 11. View Notifications: Notifications.md
    - 12. Set up the Profile: SetupProfile.md
    - 13. Sign up Free Account: FreeAccount.md
   
    - Knowledge Base:
      - Generating OpenAPI Specification (OAS) : Generating OAS.md
      - How to Add Token Generation Code : Token Generation Code.md
      - Scan APIs locally with APIsec CLI : APIsec CLI.md
      - How to Call APIsec APIs : Call APIsec APIs.md

#plugins:
 # - search
  #- git-authors


# Google Analytics	
analytics:
    gtag: G-MCT52689D6
    
    
theme:
    name: material
   
    favicon: favicon.png
    logo: logo.png
    palette:
      scheme: slate
      primary: teal
repo_url: https://github.com/apisec-inc/documentation
repo_name: apisec-in/documentation
edit_uri: ""
extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: https://www.apisec.ai/
copyright: Copyright &copy; APisec Inc.
static_templates:
    - 404.html


