site_name: Documentation
site_url: https://apisec-inc.github.io/documentation/
nav:
    - APIsec Overview: index.md
    - Getting Started: GettingStarted.md
    - 1. Register an API: 
         - Register API: RegisterAPI.md
         - Add Endpoints - UI: AddingEndpointsManually.md
         - Add Endpoints - CLI: adding-endpoints-via-cli.md
    - 2. Register an API Gateway: 
         - API Gateway Overview: RegisterGateway.md
         - Postman Set Up: setup-postman.md
         - Azure API Gateway: Configuring Azure API Management Gateway.md
    - 3. Projects Section: ProjectSection.md
    - 4. Project Dashboard: ProjectDashboard.
    - 5. Confgurations: 
        - Azure AD SSO: AzureSSOConfig.md
    - 6. Integrations: 
         - Overview: Integrations.md
         - Github Issue Tracker Set up: SetupGithubTracker.md
         - Jira Issue Tracker Set up: SetupJiraTracker.md
         - JupiterOne IT Integration: jupiter-one-integration.md
         - Linear IT Configuration: linear-it-configuration.md
         - Wrike IT Configuration: wrike-it-configuration.md
         - Synopsis Code DX Integration: synopsis-code-dx.md
    - 7. Reports: Reports.md
    - 8. Deploy Scanners: DeployScanners.md
    - 9. Vault: Vault.md
    - 10. Security Categories: 
         - APIsec Categories: SecurityCategories.md
         - Categories Use: SecurityCategoriesUse.md
    - 11. Spec Analysis: SpecAnalysis.md
    - 12. Global Dashboard: GlobalDashboard.md
    - 13. View Notifications: Notifications.md
    - 14. Profile: 
          - Set up the Profile: SetupProfile.md
          - Two-Factor Auth: 2fa.md
    - 15. Sign up Free Account: FreeAccount.md
   
    - Knowledge Base:
      - Generating OpenAPI Specification (OAS): Generating OAS.md
      - How to Add Token Generation Code: Token Generation Code.md
      - Scan APIs locally with APIsec CLI: APIsec CLI.md
      - How to Call APIsec APIs: Call APIsec APIs.md
      - Registering APIs from AWS Gateway via script: AddAPIFromAWSGateway.md
      - Securing APIsec Service Account Credentials in Vault: SecuringCredentialsExternally.md
      - Resolving Service Unavailable Error Upon User Login: UserLoginServiceUnavailable.md
      - On-Premises Sanity Test Guide: On-PremisesSanityTestGuide.md
      - Getting OAS from IBM DataPower: oas-ibm-datapower.md
      - Scanner Sizing Recommendations: scanner-sizing.md
      - Scanner Architecture: KB_ScannerNetwork.md
      - APIsec IP Acceptlist: IP-Acceptlist.md
      - K8s Scanner Deployment: k8s-scanner-deployment.md
    - Maintenance Window: maintenance-window.md
    - Service Level Agreement: ServiceLevelAgreement.md
#plugins:
 # - search
  #- git-authors


# Google Analytics	
analytics:
    gtag: G-MCT52689D6
    
    
theme:
    name: material
   
    favicon: favicon.png
    logo: logo.png
    palette:
      scheme: slate
      primary: teal
repo_url: https://github.com/apisec-inc/documentation
repo_name: apisec-in/documentation
edit_uri: ""
extra:
  generator: false
  social:
    - icon: fontawesome/solid/paper-plane
      link: https://www.apisec.ai/
copyright: Copyright &copy; APisec Inc.
static_templates:
    - 404.html


